---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devo-server
  labels:
    app: devo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devo-server
  template:
    metadata:
      labels:
        app: devo-server
    spec:
      containers:
        - image: gcr.io/ocismartdevice/devo-server
          imagePullPolicy: Always
          name: devo-server
          env:
            - name: DB_HOST
              value: devo-database
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-auth
                  key: root-password
          ports:
            - containerPort: 1337
              name: devo-websocket
            - containerPort: 3001
              name: devo-server

---
apiVersion: v1
kind: Service
metadata:
  name: devo-server
  labels:
    app: devo-server
spec:
  type: LoadBalancer
  ports:
    - port: 1337
      name: devo-websocket
    - port: 3001
      name: devo-server
  selector:
    app: devo-server
