---
apiVersion: v1
kind: Pod
metadata:
  name: devo-util
  labels:
    app: devo-util
spec:
  containers:
    - image: mysql:5.7
      name: devo-util
      command: ["/bin/bash", "-c", "while true; do sleep 60; done"]
      env:
        - name: DB_HOST
          value: devo-database
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-auth
              key: root-password
